### ISSUE TITLE
no ~/.config/mwm/config.toml file

### ISSUE THREAD

**Issue by wiiznokes** [monroeclinton/mwm#4]
```
> c r
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/mwm`
thread 'main' panicked at src/config.rs:63:10:
Unable to read config.toml file from ~/.config/mwm/config.toml: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::expect
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1034:23
   4: mwm::config::get_config
             at ./src/config.rs:62:23
   5: mwm::main
             at ./src/main.rs:140:26
   6: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I don't see any config file in the repo, so i thought i would report this issue

**Comment by wiiznokes** [comment]
Oh that on the main branch
